language: php
php:
  - 5.5
  - 5.4
  - hhvm

intstall:
  - composer install

before_script:
  - git clone git@github.com:vanilla/addons
  - vendor/bin/phpcs --config-set default_standard addons/standards/Vanilla

script:
  # Check coding standards compliance
  - vendor/bin/phpcs ./library/core
  - vendor/bin/phpcs ./applications
  - vendor/bin/phpcs ./plugins

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
