<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:23:07 **/

$LocaleInfo['29th'] = array (
  'Locale' => 'en-29th',
  'Name' => '29th Infantry Division',
  'Description' => 'Default text plus 29th customizations',
  'Version' => '1.0',
  'Author' => 'wilson29thid',
  'AuthorEmail' => 'wilson@29th.org',
  'AuthorUrl' => 'http://29th.org',
  'License' => 'MIT',
);

